export { default as LoginForm } from './auth/loginForm/loginForm'
export { default as RegisterForm } from './auth/register/register'
export { default as Header } from './header/header'

export { default as ProductDetail } from './product/ProductDetail/productDetail'
export { default as ProductList } from './product/ProductList/productList'
export { default as CreateProduct } from './CreateProduct/CreateProduct'
export { default as Category } from './Category/Category'
export { default as Cart } from './ListCart/Cart'
export { default as CheckOut } from './CheckOut/CheckOut'
export { default as Order } from './Order/Order'
export { default as OrderDetail } from './Order/OrderDetail/OrderDetail'
export { default as History } from './History/History'
export { default as HistoryDetail } from './History/HistoryDetail/HistoryDetail'
export { default as UpdateProduct } from './UpdateProduct/UpdateProduct'
